pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                dir("${env.WORKSPACE}/simple-python-pyinstaller-app"){
                    sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                dir("${env.WORKSPACE}/simple-python-pyinstaller-app"){
                    sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                dir("${env.WORKSPACE}/simple-python-pyinstaller-app"){
                    sh 'pyinstaller --onefile sources/add2vals.py'
                }
            }
            post {
                success {
                    dir("${env.WORKSPACE}/simple-python-pyinstaller-app"){
                    archiveArtifacts 'dist/add2vals'
                    }
                }
            }
        }
    }
}
